## Preprocessing

In [39]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [40]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

In [41]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [42]:
# Look at APPLICATION_TYPE value counts for binning
application_type_count = application_df['APPLICATION_TYPE'].value_counts()
application_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [43]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_type_count[application_type_count < 1064]
application_types_to_replace = application_types_to_replace.index.to_list()
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [44]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [45]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count_greater = classification_count[classification_count > 1]
classification_count_greater

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [46]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classification_to_replace = classification_count[classification_count < 1882]
classification_to_replace = classification_to_replace.index.to_list()
classification_to_replace

# # Replace in dataframe
for cls in classification_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [60]:
# Look at INCOME__AMT value counts for binning
income_amt_count = application_df['INCOME_AMT'].value_counts()
income_amt_count

0                24388
25000-99999       3747
100000-499999     3374
1M-5M              955
1-9999             728
10000-24999        543
10M-50M            240
5M-10M             185
50M+               139
Name: INCOME_AMT, dtype: int64

In [62]:
# Choose a cutoff value and create a list of income_amt to be replaced
# use the variable name `income_to_replace`
income_to_replace = income_amt_count[income_amt_count < 542]
income_to_replace = income_to_replace.index.to_list()
income_to_replace

# # Replace in dataframe
for icm in income_to_replace:
    application_df['INCOME_AMT'] = application_df['INCOME_AMT'].replace(icm,"Other")

# Check to make sure binning was successful
application_df['INCOME_AMT'].value_counts()

0                24388
25000-99999       3747
100000-499999     3374
1M-5M              955
1-9999             728
Other              564
10000-24999        543
Name: INCOME_AMT, dtype: int64

In [63]:
# Convert categorical data to numeric with `pd.get_dummies`
application_encoded = pd.get_dummies(application_df)
application_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_Other,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,1,...,0,1,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,1,...,1,0,0,1,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0

In [64]:
# Split our preprocessed data into our features and target arrays
y = application_encoded.IS_SUCCESSFUL.values
X = application_encoded.drop(columns="IS_SUCCESSFUL").values


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [65]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [69]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# Initial layer
nn_model.add(tf.keras.layers.Dense(units=6, activation="relu", input_dim=38))

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=8, activation="relu"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=8, activation="tanh"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_42 (Dense)            (None, 6)                 234

 dense_43 (Dense)            (None, 8)                 56

 dense_44 (Dense)            (None, 8)                 72

 dense_45 (Dense)            (None, 1)                 9

=================================================================
Total params: 371
Trainable params: 371
Non-trainable params: 0
_________________________________________________________________

In [70]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [71]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=150)

Epoch 1/150
804/804 [==============================] - 3s 2ms/step - loss: 0.6046 - accuracy: 0.6898
Epoch 2/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5680 - accuracy: 0.7292
Epoch 3/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5619 - accuracy: 0.7298
Epoch 4/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5599 - accuracy: 0.7311
Epoch 5/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5588 - accuracy: 0.7299
Epoch 6/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5573 - accuracy: 0.7314
Epoch 7/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5566 - accuracy: 0.7311
Epoch 8/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5560 - accuracy: 0.7308
Epoch 9/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5553 - accuracy: 0.7308
Epoch 10/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5547 - accuracy: 0.7320
Epoch 11/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5542 - accuracy: 0.7312
Epoch 12/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5537 - accuracy: 0.7309
Epoch 13/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5535 - accuracy: 0.7322
Epoch 14/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5535 - accuracy: 0.7313
Epoch 15/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5528 - accuracy: 0.7317
Epoch 16/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7317
Epoch 17/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7323
Epoch 18/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5526 - accuracy: 0.7322
Epoch 19/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5525 - accuracy: 0.7333
Epoch 20/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5520 - accuracy: 0.7331
Epoch 21/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5523 - accuracy: 0.7324
Epoch 22/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5518 - accuracy: 0.7331
Epoch 23/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5518 - accuracy: 0.7335
Epoch 24/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5516 - accuracy: 0.7330
Epoch 25/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5517 - accuracy: 0.7331
Epoch 26/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5517 - accuracy: 0.7325
Epoch 27/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5514 - accuracy: 0.7327
Epoch 28/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5512 - accuracy: 0.7339
Epoch 29/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5514 - accuracy: 0.7319
Epoch 30/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7319
Epoch 31/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5513 - accuracy: 0.7331
Epoch 32/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5510 - accuracy: 0.7335
Epoch 33/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5512 - accuracy: 0.7336
Epoch 34/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5510 - accuracy: 0.7328
Epoch 35/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5512 - accuracy: 0.7335
Epoch 36/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5510 - accuracy: 0.7322
Epoch 37/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5510 - accuracy: 0.7336
Epoch 38/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5510 - accuracy: 0.7324
Epoch 39/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5508 - accuracy: 0.7325
Epoch 40/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5506 - accuracy: 0.7335
Epoch 41/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5509 - accuracy: 0.7325
Epoch 42/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5508 - accuracy: 0.7329
Epoch 43/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5506 - accuracy: 0.7338
Epoch 44/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7336
Epoch 45/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7327
Epoch 46/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7332
Epoch 47/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5507 - accuracy: 0.7322
Epoch 48/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5503 - accuracy: 0.7335
Epoch 49/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7335
Epoch 50/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5504 - accuracy: 0.7338
Epoch 51/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5505 - accuracy: 0.7324
Epoch 52/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5506 - accuracy: 0.7337
Epoch 53/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5504 - accuracy: 0.7335
Epoch 54/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7339
Epoch 55/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7326
Epoch 56/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5500 - accuracy: 0.7335
Epoch 57/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7336
Epoch 58/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7329
Epoch 59/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7334
Epoch 60/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7341
Epoch 61/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7332
Epoch 62/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7341
Epoch 63/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5499 - accuracy: 0.7339
Epoch 64/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7338
Epoch 65/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7336
Epoch 66/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7326
Epoch 67/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7326
Epoch 68/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7344
Epoch 69/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7343
Epoch 70/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5494 - accuracy: 0.7346
Epoch 71/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7335
Epoch 72/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7335
Epoch 73/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7339
Epoch 74/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7343
Epoch 75/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7343
Epoch 76/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7340
Epoch 77/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5491 - accuracy: 0.7341
Epoch 78/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7338
Epoch 79/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7338
Epoch 80/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7344
Epoch 81/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7338
Epoch 82/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7340
Epoch 83/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7339
Epoch 84/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5492 - accuracy: 0.7333
Epoch 85/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7345
Epoch 86/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7332
Epoch 87/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7339
Epoch 88/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7342
Epoch 89/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7341
Epoch 90/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7342
Epoch 91/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5491 - accuracy: 0.7339
Epoch 92/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7338
Epoch 93/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7339
Epoch 94/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7343
Epoch 95/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7334
Epoch 96/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7333
Epoch 97/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5491 - accuracy: 0.7333
Epoch 98/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5492 - accuracy: 0.7347
Epoch 99/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7339
Epoch 100/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7335
Epoch 101/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7343
Epoch 102/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7339
Epoch 103/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7340
Epoch 104/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7337
Epoch 105/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5490 - accuracy: 0.7338
Epoch 106/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7344
Epoch 107/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5493 - accuracy: 0.7336
Epoch 108/150
804/804 [==============================] - 4s 5ms/step - loss: 0.5492 - accuracy: 0.7340
Epoch 109/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5492 - accuracy: 0.7338
Epoch 110/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7339
Epoch 111/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7345
Epoch 112/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5493 - accuracy: 0.7347
Epoch 113/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7352
Epoch 114/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7349
Epoch 115/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7341
Epoch 116/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5491 - accuracy: 0.7345
Epoch 117/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7346
Epoch 118/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7346
Epoch 119/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7343
Epoch 120/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7350
Epoch 121/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7342
Epoch 122/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7339
Epoch 123/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7339
Epoch 124/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7342
Epoch 125/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7341
Epoch 126/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7342
Epoch 127/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7348
Epoch 128/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7348
Epoch 129/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7338
Epoch 130/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7341
Epoch 131/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7344
Epoch 132/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5488 - accuracy: 0.7350
Epoch 133/150
804/804 [==============================] - 3s 4ms/step - loss: 0.5489 - accuracy: 0.7358
Epoch 134/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7345
Epoch 135/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7338
Epoch 136/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5487 - accuracy: 0.7348
Epoch 137/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7346
Epoch 138/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7345
Epoch 139/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7339
Epoch 140/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7339
Epoch 141/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7341
Epoch 142/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7347
Epoch 143/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5487 - accuracy: 0.7348
Epoch 144/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7350
Epoch 145/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7352
Epoch 146/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7350
Epoch 147/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7344
Epoch 148/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7348
Epoch 149/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7343
Epoch 150/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7349

In [72]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5613 - accuracy: 0.7245 - 487ms/epoch - 2ms/step
Loss: 0.5612895488739014, Accuracy: 0.7245481014251709

In [73]:
# Export our model to HDF5 file
nn_model.save('AlphabetSoupCharity_Optimization.h5')