## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_count = application_df['APPLICATION_TYPE'].value_counts()
application_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_type_count[application_type_count < 527]
application_types_to_replace = application_types_to_replace.index.to_list()
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_count = application_df['CLASSIFICATION'].value_counts()
classification_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count_greater = classification_count[classification_count > 1]
classification_count_greater

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classification_to_replace = classification_count[classification_count < 1882]
classification_to_replace = classification_to_replace.index.to_list()
classification_to_replace

# # Replace in dataframe
for cls in classification_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_encoded = pd.get_dummies(application_df)
application_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = application_encoded.IS_SUCCESSFUL.values
X = application_encoded.drop(columns="IS_SUCCESSFUL").values


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# Intiial layer
nn_model.add(tf.keras.layers.Dense(units=6, activation="relu", input_dim=43))

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=6, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 6)                 264

 dense_1 (Dense)             (None, 6)                 42

 dense_2 (Dense)             (None, 1)                 7

=================================================================
Total params: 313
Trainable params: 313
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6566 - accuracy: 0.6621
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5661 - accuracy: 0.7248
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5588 - accuracy: 0.7266
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5560 - accuracy: 0.7284
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7310
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5530 - accuracy: 0.7325
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5524 - accuracy: 0.7317
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5520 - accuracy: 0.7313
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7318
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5509 - accuracy: 0.7323
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5502 - accuracy: 0.7311
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5505 - accuracy: 0.7318
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5498 - accuracy: 0.7325
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7337
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7340
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7344
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7341
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7344
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5482 - accuracy: 0.7349
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7353
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7347
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7348
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5478 - accuracy: 0.7343
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7351
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7346
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7355
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7351
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7350
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7341
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7351
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5471 - accuracy: 0.7353
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7354
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7353
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7347
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7358
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7350
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7352
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7350
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7358
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7359
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7354
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7361
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7365
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7363
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7358
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7348
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7350
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7351
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7362
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7352
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5466 - accuracy: 0.7364
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7361
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7355
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7357
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7351
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7362
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7363
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7366
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5465 - accuracy: 0.7358
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7362
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7365
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5464 - accuracy: 0.7351
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7358
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7358
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7352
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7353
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7362
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7359
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7357
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7364
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7358
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7347
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7353
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7360
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7358
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7345
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7352
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7353
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7365
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7353
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7352
Epoch 82/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7361
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7359
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7357
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7364
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7359
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7355
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7352
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7355
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7350
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7357
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7358
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7359
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7355
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7358
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7362
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7371
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7357
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7353
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7366

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5555 - accuracy: 0.7262 - 455ms/epoch - 2ms/step
Loss: 0.5554757714271545, Accuracy: 0.7261807322502136

In [17]:
# Export our model to HDF5 file
nn_model.save('AlphabetSoupCharity.h5')